### ISSUE TITLE
Change callback list in DynamicProperty to a list of WeakReference

### ISSUE THREAD

**Issue by howardyuan** [Netflix/archaius#163]
Currently, all callbacks for a DynamicProperty is maintained in a list. Since DynamicProperty itself is static, it never goes away. Therefore, the callback list it holds never goes away. And that in turn dictates all those Dynamicproperty wrappers not eligible for GC.

There's a new interface function removeAllCallbacks() to explicitly remove all callbacks. However, changing the callback list to list of WeakReference will give GC a change to reclaim those fastproperty wrappers in time even if removeAllCallbacks() is not explicitly called.

**Comment by utk4rsh** [comment]
Hey Howard,

We are using Archaius for configuration management in a batch application which uses Apache Spark. The spark job usually take long duration to execute during which it reads the configuration property whenever needed.  However after certain point of team, there is enormous GC activity because most of the heap is filled by DynamicProperty instances which were never GCed. 

Would like to know your view on this. You mentioned the removeAllCallbacks() method to explicitly remove all callbacks. Could you help us with the guidelines on using it or any other way to avoid this problem?

**Comment by howardyuan** [comment]
@utk4rsh One thing that's hard to change for Archaius V1 is its static nature. I took a stab at trying to make properties GC'able but didn't succeed. I haven't looked at this since. It's one of the primary motivations for us to come up with Archaius V2.
That being said, I suspect there maybe some ways that you can improve your usage of properties so you don't exhaust heap. The static nature of properties has been there since beginning and I don't hear people exhaust heap because of it. One thing I can think of is that you create a new DynamicProperty every time. Even though the underneath is still static, there is a wrapper object being created and that will not be GC'ed. A better practice is to go through DynamicPropertyFactory and get the property by name. That way, you can be sure there's one object created per property. Unless you've millions of properties, you won't run into memory issue. Give it a try and let us know how it goes.

**Comment by utk4rsh** [comment]
Thanks @howardyuan for the inputs. We would try out what you suggested and post any further findings that could be helpful to all.
