### ISSUE TITLE
DynamicStringProperty removes spaces in strings containing list separator

### ISSUE THREAD

**Issue by matveym** [Netflix/archaius#417]
public static void main(String[] args) {
        DynamicConfiguration configuration = new DynamicConfiguration((initial, checkPoint) -> {
            if (initial) {
                return PollResult.createFull(ImmutableMap.of("a", "1, 2"));
            }
            return PollResult.createFull(ImmutableMap.of("a", "3, 4"));
        }, new ExplicitCallScheduler());
        ConfigurationManager.install(configuration);
        DynamicStringProperty a = new DynamicStringProperty("a", null);
        System.out.println(a.get());
        ExplicitCallScheduler.pollingRunnable.run();
        System.out.println(a.get());
    }

    public class ExplicitCallScheduler extends AbstractPollingScheduler {
        public static Runnable pollingRunnable;

        @Override
        protected void schedule(Runnable pollingRunnable) {
             this.pollingRunnable = pollingRunnable;
        }

        @Override
        public void stop() {
        }
    }

Output:
1,2
3, 4

**Comment by howardyuan** [comment]
@matveym The discrepancy that you noted here is due to the difference between how properties are stored in a static configuration and dynamic poller based configuration. In the initial load phase ("1, 2" case), the properties are fed to abstract configuration and stored as a list of strings with the space stripped since they're delimited and the way of abstract configuration stores. When you retrieve the property as a single string, it's re-concatenated for you but without the space anymore. However, in the subsequent polling, the properties are treated as strings as is without even being splitted. I guess the rationale is that you control the poller logic and if you want consistent behaviors, you can implement poller logic to strip out spaces and re-concatenated.

**Comment by matveym** [comment]
@howardyuan Indeed I could strip out spaces myself, thanks a lot for the suggestion.
