### ISSUE TITLE
Why archaius need to declare Dynamic Property firstly？

### ISSUE THREAD

**Issue by wuxianInfi** [Netflix/archaius#499]
Why archaius need to declare Dynamic Property firstly？
Can I use such code as following in my method directly?

void myMethod(){
String v = DynamicPropertyFactory.getInstance().getStringProperty("key1", "default").get();
}

**Comment by brharrington** [comment]
If you follow that pattern, then there isn't any reason to use DynamicProperty. Just get the value from the config directly. I think you will have a memory leak with the code above because it registers callbacks for each instance of the dynamic property that is created (see [the comment](https://github.com/Netflix/archaius/blob/master/archaius-core/src/main/java/com/netflix/config/DynamicProperty.java#L51)).

**Comment by wuxianInfi** [comment]
Can I use a cache(e.g ConcurrentHashMap) to store the DynamicProperty to avoid the memory leak problem?

**Comment by wuxianInfi** [comment]
If we don't use callback, should it works rightly? Or can we use a cache (e.g. ConcurrentHashMap) to store the created PropertyWrapper(DynamicStringProperty) to void the memory leak problem?

**Comment by rgallardo-netflix** [comment]
V1 is deprecated and won't be maintained anymore.
